# Generated by Django 5.2.13 on 2026-05-28 13:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Afro Night — Édition juin 2026", max_length=200
                    ),
                ),
                (
                    "venue",
                    models.CharField(
                        default="La Péniche, 02 quai de la Tournelle, 75005 Paris",
                        max_length=300,
                    ),
                ),
                ("date", models.DateField()),
                ("capacity", models.PositiveIntegerField(default=300)),
                ("opening_time", models.TimeField(default="23:00")),
                ("closing_time", models.TimeField(default="05:00")),
                (
                    "venue_total_ht",
                    models.DecimalField(decimal_places=2, default=4000, max_digits=10),
                ),
                (
                    "venue_total_ttc",
                    models.DecimalField(decimal_places=2, default=4800, max_digits=10),
                ),
                (
                    "venue_deposit",
                    models.DecimalField(decimal_places=2, default=3000, max_digits=10),
                ),
                (
                    "venue_balance",
                    models.DecimalField(decimal_places=2, default=1800, max_digits=10),
                ),
                (
                    "venue_caution",
                    models.DecimalField(decimal_places=2, default=2000, max_digits=10),
                ),
                (
                    "tpe_commission",
                    models.DecimalField(decimal_places=4, default=0.065, max_digits=5),
                ),
                (
                    "sacem_rate",
                    models.DecimalField(decimal_places=4, default=0.039, max_digits=5),
                ),
                ("venue_approval_required", models.BooleanField(default=True)),
                ("venue_approval_received", models.BooleanField(default=False)),
                ("staff_count", models.PositiveIntegerField(default=20)),
                ("vip_invited_count", models.PositiveIntegerField(default=20)),
                (
                    "vip_cost_per_person",
                    models.DecimalField(decimal_places=2, default=15, max_digits=6),
                ),
                ("deposit_deadline", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="BudgetLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "timing",
                    models.CharField(
                        choices=[
                            ("avant", "Avant J"),
                            ("nuit", "Nuit J"),
                            ("post", "Post-soirée"),
                        ],
                        default="avant",
                        max_length=10,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("revenue", "Recettes"),
                            ("fixed", "Dépenses fixes"),
                            ("human", "Dépenses humaines"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "is_calculated",
                    models.BooleanField(
                        default=False, help_text="Calculé automatiquement"
                    ),
                ),
                ("is_optional", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_lines",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["section", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="InstagramPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("days_before", models.IntegerField(help_text="J-x avant l'événement")),
                ("phase", models.CharField(max_length=50)),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("Post", "Post (feed)"),
                            ("Reel", "Reel (vidéo)"),
                            ("Story", "Story (éphémère)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "cta",
                    models.CharField(max_length=300, verbose_name="Call to Action"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("pending_approval", "En attente accord venue"),
                            ("approved", "Approuvé"),
                            ("published", "Publié"),
                        ],
                        default="pending_approval",
                        max_length=20,
                    ),
                ),
                ("venue_approval_required", models.BooleanField(default=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instagram_posts",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="PricingPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase_code",
                    models.CharField(
                        choices=[
                            ("seb", "Super Early Bird"),
                            ("eb", "Early Bird"),
                            ("pv", "Pré-vente"),
                            ("lm", "Last Minute"),
                            ("door", "Sur place"),
                        ],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("price_solo", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "price_girls_group",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("girls_group_size", models.PositiveIntegerField(default=4)),
                (
                    "price_duo_mixed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "price_door_23h",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "price_door_00h",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "price_door_after_01h",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("perks", models.JSONField(blank=True, default=list)),
                ("stock_solo", models.PositiveIntegerField(default=0)),
                ("stock_girls_lots", models.PositiveIntegerField(default=0)),
                ("stock_duo_lots", models.PositiveIntegerField(default=0)),
                ("sold_solo", models.PositiveIntegerField(default=0)),
                ("sold_girls_lots", models.PositiveIntegerField(default=0)),
                ("sold_duo_lots", models.PositiveIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_phases",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
                "unique_together": {("event", "phase_code")},
            },
        ),
        migrations.CreateModel(
            name="TicketSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sale_date", models.DateField()),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[
                            ("solo", "Solo"),
                            ("girls_group", "Groupe filles"),
                            ("duo_mixed", "Duo mixte"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "gender",
                    models.CharField(
                        choices=[("F", "Femme"), ("M", "Homme")], max_length=1
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_sales",
                        to="events.event",
                    ),
                ),
                (
                    "pricing_phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="events.pricingphase",
                    ),
                ),
            ],
            options={
                "ordering": ["sale_date"],
            },
        ),
        migrations.CreateModel(
            name="SimulationScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scenario_type",
                    models.CharField(
                        choices=[
                            ("pessimistic", "Pessimiste"),
                            ("neutral", "Neutre"),
                            ("optimistic", "Optimiste"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_pax", models.PositiveIntegerField(default=200)),
                (
                    "bar_spend_per_person",
                    models.DecimalField(decimal_places=2, default=25, max_digits=6),
                ),
                (
                    "tpe_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=60,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "alcohol_cost",
                    models.DecimalField(decimal_places=2, default=2000, max_digits=10),
                ),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "net_result",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "margin_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenarios",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "scenario_type")},
            },
        ),
        migrations.CreateModel(
            name="VIPTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "formula",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (250, "250 € — 4 personnes"),
                            (500, "500 € — 5 personnes"),
                            (650, "650 € — 5 personnes"),
                            (1000, "1 000 € — 5 personnes"),
                            (1500, "1 500 € — 5 personnes (VIP unique)"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "double_order",
                    models.BooleanField(default=False, help_text="×2 ressert"),
                ),
                (
                    "promo_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("promoter_name", models.CharField(blank=True, max_length=100)),
                ("is_booked", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vip_tables",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["table_number"],
                "unique_together": {("event", "table_number")},
            },
        ),
    ]
