# Generated by Django 5.2.13 on 2026-06-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="instagrampost",
            name="assigned_to",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Qui"
            ),
        ),
    ]
