# Generated by Django 5.2.13 on 2026-06-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_instagrampost_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="instagrampost",
            name="people_names",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Noms"
            ),
        ),
        migrations.AlterField(
            model_name="instagrampost",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("Post", "Post (feed)"),
                    ("Reel", "Reel (vidéo)"),
                    ("Story", "Story (éphémère)"),
                    ("Repost", "Repost (partage)"),
                ],
                max_length=10,
            ),
        ),
    ]
